config/routes.rb
Rails.application.routes.draw do

  root 'pages#landing'
  get '/pull_messages' => 'pages#pull_messages'
  get '/link_to_twitter' => 'pages#twitter_sync'
  get '/auth/twitter/callback' => 'pages#twitter_callback'
  get '/googleauth' => 'pages#googleauth'
  get '/callback'=> 'pages#callback'
  post '/send' => 'messages#send_mail'
  get 'newsfeed' => 'pages#newsfeed'
  post '/direct_messages' => 'messages#create_direct_message'
  post '/tweets' => 'messages#create_tweet'
  get '/reminders' => 'reminders#index'
  get '/import_contacts' => "pages#import"
  get '/permission' => "pages#permission"
  resources :users, only: [:create, :update,:show]

  resources :contacts, only: [:show, :create, :destroy, :update, :index, :edit]

  resources :sessions, only: [:create, :destroy]

end

app/views/pages/analytics.html.erb
<!-- <h1>Message Analytics</h1>

<ul>
  <%# @messages.each do |message| %>
    <li>Message From: <%#= current_user.contacts.where(id:message.contact_id).first["name"] %></li>
    <li>Message Sent At: <%#= DateTime.strptime(message.time_stamp.to_s, '%s') %></li>
    <li>Message Snippet: <%#= message.summary %></li>
    <li>Your message breakdown is <%#= message.easytoner %></li>
    <li>Your message has the following Sentiment: <strong><%#= message.check_sentiment%></strong><br /><br />
  <%# end %>
</ul> -->

app/views/pages/import.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    <%= render :partial => "import.js" %>
  </script>
<% end %>

<h1 class='remindertitle'> Import Contacts </h1><br>
<!-- <h3 style="text-align:center;margin-top:10px;"> Please select all contacts you would like to keep in touch with </h3><br> -->
<p style="text-align: center;">Number of contacts chosen: <span class='number_of_selected_contacts'>0</span><p>
<a href="/" id="import_contact_button">Submit</a>

<div style='text-align: center;'>
  <%= form_tag '/import_contacts',id:"search_imported_contacts" do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search for contact", class: 'import-search-bar'%>
  <% end %>
</div>

<div class="potential-contacts-container">
</div>

app/views/pages/landing.html.erb
<% unless current_user %>

  <% if flash[:signup_modal] %>
    <script type='text/javascript'>
      $(document).on('ready', function() {
        $('.sign-up-modal').css('display', 'block');
        $('.sign-up-heading-error').html('Please fill out the form completely');
        setTimeout(function(){
          $('.sign-up-heading-error').html('');
        }, 5000);
      });
    </script>
  <% end %>

  <div class="sign-up-modal">
    <div class="sign-up-form">
      <%= form_for @user do |f| %>
        <button type="button" class="close">x</button>
        <div class="sign-up-user">
          <h3 class="sign-up-heading">SIGN UP</h3>
          <h4 class='sign-up-heading-error'></h4>
        </div>
        Name  <br><%= f.text_field :name, class: 'signup-modal-field', placeholder: "eg. John Doe"%><br>
        Phone (optional) <br><%= f.text_field :phone,  class: 'signup-modal-field', placeholder: "416 676 9999" %><br>
        Email  <br><%= f.email_field :email, class: 'signup-modal-field', id: 'email-signup', placeholder: "johndoe@gmail.com" %><br>
        Password <br><%= f.password_field :password, class: 'signup-modal-field', id: 'signup-field',placeholder: "**********" %><br>
        Password Confirmation <br><%= f.password_field :password_confirmation, class: 'signup-modal-field', id: 'signup-confirmation',placeholder: "**********"  %><br>
        <%= f.submit "Create Account", class: 'modal-submit', id: 'modal-submit-create'%>
      <% end %>
    </div>
  </div>
<% end %>

<% if flash[:login_modal] %>
  <script type='text/javascript'>
    $(document).on('ready', function() {
      $('.login-modal').css('display', 'block');
      $('.login-heading-error').html('Username or password is invalid!');
      setTimeout(function(){
        $('.login-heading-error').html('');
      }, 5000);
    });
  </script>
<% end %>

<% if flash[:login_modal_2] %>
  <script type='text/javascript'>
    $(document).on('ready', function() {
      $('.login-modal').css('display', 'block');
      $('.login-heading-error').html("you aren't logged in, please log in");
      setTimeout(function(){
        $('.login-heading-error').html('');
      }, 5000);
    });
  </script>
<% end %>

  <div class="login-modal">
    <div class="login-form">
      <%= form_tag sessions_path do %>
      <button type="button" class="close">x</button>
      <div class="sign-up-user">
        <h3 class="sign-up-heading">LOG IN</h3>
        <h4 class='login-heading-error'></h4>
      </div>
          <%= label_tag :email %><br>
          <%= email_field_tag :email, params[:email], placeholder: "eg. johndoe@gmail.com", class: 'field'%>
          <%= label_tag :password %><br>
          <%= password_field_tag :password, nil, class:'field'%>
        <%= submit_tag "Log In", class: 'modal-submit', id: 'modal-submit-login' %>
      <% end %>
    </div>
  </div>



<!-- Section 1: Navigation Bar (See: application.html.erb) *CSS located in 'landingpage.scss'* -->


<!-- Section 2: The following is the photo background w text & sign up button -->
  <!-- <%= video_tag "video.mp4", :controls => false, autoplay: :autoplay, loop: :loop, id:"photo-background"%> -->
  <div class="photo-background-image">
    <div class="photo-background">
    <div class="welcome-text">
      <p id="main-heading">Keep in touch no matter where life takes you</p>
      <p id="second-heading">Remindr makes it easy to keep in touch with friends, family and your networking connections.</p>
    </div>

      <a class="getstarted">START CONNECTING</a>
    </div>

  </div>

<!-- Section 3: The following are the 3 main selling points of the app -->

  <ul id="sellingPoints">

    <li id="sellingPoint1" class="selling-points">
      <%= image_tag "message.svg", class:"icon" %>
        <h3>EASY</h3>
        <p>Access all your messages from twitter and gmail, with one click of a button.</p>
    </li>

    <li id="sellingPoint2" class="selling-points">
      <%= image_tag "clock.svg", class:"icon" %>
        <h3>FAST</h3>
          <p>Receive and deliver messsages quickly and simply.</p>
    </li>

    <li id="sellingPoint3" class="selling-points">
      <%= image_tag "ring.svg", class:"icon" %>
        <h3>CUSTOMIZE</h3>
        <p>Choose how you want to get your notifications; text or email.</p>
    </li>
  </ul>


<!-- Section 4: Step by step explanation of the app; everything falls under the 'stepbystep'div -->
<div id="stepbystep">
  <div id="step-contents-div">
    <h1 id="stepbystepHeading">HOW IT WORKS</h1>

    <div class="left-div">
      <div class="text-div">
      <div class="number-div" id="first-number">
        <p class="number">1</p>
      </div>
      <div class="step-text-div">
      <p class="step-text">Add all your contacts and social media accounts that you want to keep in touch with.</p>
      </div>
      </div>
    </div>

    <div class="right-div">
      <div class="step-icon-div">
          <%= image_tag "user.svg", id:"add-user-icon" %>
      </div>
    </div>

    <div class="left-div">
      <div class="step-icon-div">
        <%= image_tag "calendar.svg", id:"add-user-icon" %>
      </div>
    </div>
    <div class="right-div">
      <div class="text-div">
      <div class="number-div" id="second-number">
        <p class="number">2</p>
      </div>
      <div class="step-text-div">
      <p class="step-text">Customize your reminders for when you want to be notified to keep in touch with your contacts.</p>
      </div>
    </div>
    </div>

    <div class="left-div">
      <div class="text-div">
      <div class="number-div" id="third-number">
        <p class="number">3</p>
      </div>
      <div class="step-text-div">
      <p class="step-text">Import your messages from Gmail and Twitter.</p>
      </div>
    </div>
    </div>

    <div class="right-div">
      <div class="step-icon-div">
        <%= image_tag "mail.svg", id:"add-user-icon" %>
      </div>
    </div>


    <div class="left-div">
      <div class="step-icon-div">
        <%= image_tag "chat.svg", id:"add-user-icon" %>
      </div>
    </div>

    <div class="right-div">
      <div class="text-div">
      <div class="number-div" id="fourth-number">
        <p class="number">4</p>
      </div>
      <div class="step-text-div">
      <p class="step-text">Get notified via text or email to keep in touch and message directly through our platform.</p>
      </div>
    </div>
    </div>



  </div>
</div>


<!-- Section 4: The following is the final div of the landing page -->

  <div id="landingBottom">
    <h1 id="textHeading">Ready to join?</h1>
      <a class="getstarted" id="bottom-button">START CONNECTING</a>
  </div>

  <div class="footer">
    <ul class="left-list">
        <li class="left-list-link">Help</li>
        <li class="left-list-link">About</li>
        <li class="left-list-link">Careers</li>
        <li class="left-list-link">Press</li>
        <li class="left-list-link">Blog</li>
        <li class="left-list-link">Contact Us</li>
    </ul>
    <ul class="middle-list">
        <li class="middle-list-link">LOCATIONS</li>
        <li class="middle-list-link">Toronto</li>
        <li class="middle-list-link">New York - Coming Soon</li>
        <li class="middle-list-link">Boston - Coming Soon</li>
        <li class="middle-list-link">San Francisco - Coming Soon</li>
        <li class="middle-list-link">Las Vegas - Coming Soon</li>
    </ul>
    <div class="logo-footer">
      <p class="logo-footer-text">Remindr</p>
    </div>
    <div class="divider"></div>
    <ul class="bottom-footer-list">
      <li class="bottom-list-link">Privacy</li>
      <li class="bottom-list-link">Cookies</li>
      <li class="bottom-list-link">Terms</li>
      <li class="bottom-list-link" id='bottom-list-right'>2016 Remindr. All rights reserved.</li>

    </ul>
  </div>

app/views/pages/login_page.html.erb
<div class="social-link-page">
  <div class='reminder-background'></div>
  <div style='text-align: center; font-size: 3em; color:white'>Hold on tight, you're almost there. Last step: Link your Twitter account!</div>
  <div class="sign-in-link">
    <!-- <div class="google-login"><div class="logo-image"><%= image_tag "gmail-logo.svg", class:"gmail-logo" %></div><%= link_to 'Import messages from Gmail', '/googleauth', class: 'sm-link'%></div> -->
    <div class="twitter-login"><div class="logo-image"><%= image_tag "twitter-logo.svg", class:"twitter-logo" %></div><%= link_to 'Import messages from Twitter', '/auth/twitter', class: 'sm-link' %></div>
      <%= link_to '(skip this step)', "/permission", class:'skip_twitter_auth' %>
  </div>
</div>

app/views/pages/newsfeed.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    <%= render partial: "newsfeed_left_pane.js" %>
  </script>
<% end %>
<%= link_to "click to reload messages", pull_messages_path, remote: true, class: "reload-icon", id: "reload-messages"%>

<div class='loading-modal'>
  <div class='inner-loading-modal'>Getting new messages...</div>
</div>

<!-- Section 1: Navigation Bar (see: application.html.erb & landingpage.scss)  -->



<!-- 'main-container' contains everything on the page except the navigation bar at the top of the page -->
<div class="main-container">


<!-- Section 3: List of All Contacts (left 25% of the page)  -->
  <div class="contacts-container">
    <div class="searchbar-with-icons-div">
      <!-- <a href=#>
      <div class="filter-icon">
        <%= image_tag "filter.png" %>
      </div>
      </a> -->
      <div class="search-contacts-bar">
        <%= form_tag contacts_path,id:"search_contact" do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search contacts", class: 'search-bar-field'%>
        <% end %>
      </div>
      <!-- <a href=#>
        <div class="add-icon">
        <%= image_tag "add-contact.png" %>
        </div>
      </a> -->
    </div>
<!-- 'List of Contacts/Messages' div -->
  <div id='load_contact_box'>
      <div class="contacts-messages">
      </div>
    </div>
</div>
<!-- The last </div> directly above corresponds to the 'contacts container' div at the start of Section 3 -->


<!-- 'contact-info-updating-container' contains everything to the right of the 'List of All Contacts' div  -->
<!-- 'contact-info-updating-container' contains the right 75% of the page -->

<!-- Section 4: All messages received from individual contact (middle 50% of page) -->
  <div class="contact-info-updating-container">
    <div class="messages">
      <div id="message-content">
      <% #Messages of contact you click on %>
      </div>
        <!-- send direct message via twitter  -->
        <!-- <div class-"send-twitter-div"> -->
          <!-- <div class="send-direct-message">
              <%= form_tag "/", id:"send-direct-message" do %>
                <%= hidden_field_tag "receiver-twitter-user", nil, id:"twitter-user-field"%>
                <%= label_tag "direct_message", "Twitter Direct Message: ", class:"message-label" %><br>
                <%= text_area_tag "direct_message", nil, class:"twitter_field", id: 'twitter-text-area'  %>
                <div class="send-dm-submit">
                <%= submit_tag "Send"%>
                </div>
              <% end %>
          </div> -->

          <!-- <div class="send-tweet">
            <%= form_tag '/', id:'send-tweet' do %>
            <%= label_tag "tweet_message", "Tweet:", class:"message-label" %><br>
            <%= text_area_tag "tweet_message", nil, class:"twitter_field",id: 'send-text-area' %>
            <div class="send-tweet-submit">
            <%= submit_tag "Send" %>
            </div>
            <% end %>
          </div> -->
        <!-- </div> -->

        <!-- send email  -->
      <div id='message-div-small'>Click to send a message!</div>

      <div id='toggle-message-div'>
        <div class='gmail-toggle'>Gmail</div>
        <div class='twitter-toggle'>Twitter Direct Message</div>
        <div class='text-toggle'>Tweet</div>

        <div class="send-email-div">
          <%= form_tag "/", id:"send_email" do %>
            <%= hidden_field_tag "receiver", nil, id:"email_field"%>
            <%= label_tag "subject", "Subject:" %><br>
            <%= text_field_tag "subject", nil, id:"subject_field" %><br>

            <%= label_tag "body", "Body:" %><br>
            <%= text_area_tag "body", nil, id:"body_field" %><br>

            <%= submit_tag "Send" , id:'submit_field' %>

          <% end %>
          <div class='close-message-pane'>hide message pane</div>
        </div>

        <div class="send-direct-message">
            <%= form_tag "/", id:"send-direct-message" do %>
              <%= hidden_field_tag "receiver-twitter-user", nil, id:"twitter-user-field"%>
              <%= label_tag "direct_message", "Twitter Direct Message: ", class:"message-label" %><br>
              <%= text_area_tag "direct_message", nil, class:"twitter_field", id: 'twitter-text-area'  %>
              <div class="send-dm-submit">
              <%= submit_tag "Send"%>
              </div>
            <% end %>
            <div class='close-message-pane'>hide message pane</div>
        </div>

        <div class="send-tweet">
          <%= form_tag '/', id:'send-tweet' do %>
          <%= label_tag "tweet_message", "Tweet:", class:"message-label" %><br>
          <%= text_area_tag "tweet_message", nil, class:"twitter_field",id: 'send-text-area' %>
          <div class="send-tweet-submit">
          <%= submit_tag "Send" %>
          </div>
          <% end %>
        <div class='close-message-pane'>hide message pane</div>
        </div>
      </div>
    </div>
</div>

app/views/pages/permission.html.erb
<div class="social-link-page">
  <div class='reminder-background'></div>
  <div style='text-align: center; font-size: 3em; color:white'>Last thing and you're all set!</div>
  <div class="sign-in-link">
    <div class="google-login"><div class="logo-image"><%= image_tag "gmail-logo.svg", class:"gmail-logo" %></div><%= link_to 'Import Contacts From Google', import_contacts_path, class: 'sm-link'%></div>
  </div>
</div>

app/views/pages/pull_messages.js.erb
location.reload()

app/views/pages/tweet_info.html.erb
 <h1>this is the page that loads after method is called that I need to test for rake </h1>

app/views/pages/twitter_sync.html.erb
<div class="social-link-page">
  <div class='reminder-background'></div>
  <div style='text-align: center; font-size: 3em; color:white'>Hold on tight, you're almost there. Last step: Link your Twitter account!</div>
  <div class="sign-in-link">
    <div class="twitter-login"><div class="logo-image"><%= image_tag "twitter-logo.svg", class:"twitter-logo" %></div><%= link_to 'Import messages from Twitter', '/auth/twitter', class: 'sm-link' %></div>
      <%= link_to '(skip this step)', "/newsfeed_path", class:'skip_twitter_auth' %>
  </div>
</div>