config/routes.rb
Rails.application.routes.draw do

  root 'pages#landing'
  get '/pull_messages' => 'pages#pull_messages'
  get '/link_to_twitter' => 'pages#twitter_sync'
  get '/auth/twitter/callback' => 'pages#twitter_callback'
  get '/googleauth' => 'pages#googleauth'
  get '/callback'=> 'pages#callback'
  post '/send' => 'messages#send_mail'
  get 'newsfeed' => 'pages#newsfeed'
  post '/direct_messages' => 'messages#create_direct_message'
  post '/tweets' => 'messages#create_tweet'
  get '/reminders' => 'reminders#index'
  get '/import_contacts' => "pages#import"
  get '/permission' => "pages#permission"
  resources :users, only: [:create, :update,:show]

  resources :contacts, only: [:show, :create, :destroy, :update, :index, :edit]

  resources :sessions, only: [:create, :destroy]

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates :name, :user_id, presence: true

  has_many :messages
  has_many :reminders
  belongs_to :user

  #email a user's contacts that have been neglected
  def reach_out
    case user.reach_out_platform
      when "Email"
        Misc.send_mail(user, contact.email, "It's been a while...",user.automated_message)
      when "Twitter"
        Misc.send_dm(self, contact)
    end
  end

  #Load a contact's direct messages from twitter
  def get_dms(user_client)
    dms = []
    # loop through messages and store them in dms array
    user_client.direct_messages_sent(options = {}).each do |direct_message|
      if direct_message.recipient.screen_name == self.twitter_username
        message = {}
        message['time_stamp'] = direct_message.created_at.to_i
        message['text'] = direct_message.text
        dms << message
      end
    end
    dms
  end


  #Called during scheduled task to get the most recent interaction with every contact
  def self.update
    all_contacts = Contact.all
    all_contacts.each do |contact|
      contact.get_most_recent_message
    end
  end

  #Get five most recent tweets or dms
  def get_most_recent_messages
    message_list = []
    #Check if email exists for contact
    if google_id
      message_list += get_email
    end

    #Check if the user is synched with twitter
    if user.token
      message_list += get_dms(user.twitter_client)
    end

    if message_list.length > 0
      sorted = potential_messages.sort_by{|message| message['time_stamp']}.reverse
      Message.destroy_all(contact_id: id)
      i=0
      while i<=4 && i < sorted.length
        Message.create(user_id: user.id, contact_id: id, time_stamp: sorted[i]['time_stamp'], body_plain_text: sorted[i]['text'], body_html: sorted[i]['html'], snippet: sorted[i]['snippet'])
        i+= 1
      end

    else
      if messages.all.length == 0
      # Create a message with no body to start countdown of 30 days if there is no email for contact
      Message.create(time_stamp:Time.now.to_i, contact_id: id, user_id: user.id, body_plain_text: "~", snippet: 'No available messages')
      end
    end
  end

  #Get all emails to and from a contact
  def get_email
    #Get new token for the user associated with contact if expired
    user.check_token
    token = user.access_token
    user_google_id = user.google_id
    #Query gmail to find email_id of last email
    email_ids = search_email(user_google_id, token)
    #Past interactions exist
    if email_ids
      emails = []
      #Find email body an message details
      email_ids.each do |id|
        emails << fetch_email(user_google_id, token, id)
      end
      return emails

    else
      return []
    end
  end

  #Finds email id of most recent outbound email from user to contact
  def search_email(user_google_id, token)
    #search string
    query= "to:#{email}"
    query_email_api_url = "https://www.googleapis.com/gmail/v1/users/#{user_google_id}/messages?maxResults=5&q=#{query}&access_token=#{token}"
    #True if there are past interactions on email
    if JSON.parse(RestClient.get(query_email_api_url))['messages']
      email_ids = []
      JSON.parse(RestClient.get(query_email_api_url))['messages'].each do |message|
        email_ids << message['id']
      end
      return email_ids
    else
      return nil
    end
  end

  #Gets email body given the email_id
  def fetch_email(user_google_id, token, email_id)
    api_url = "https://www.googleapis.com/gmail/v1/users/#{user_google_id}/messages/#{email_id}?access_token=#{token}"
    email = JSON.parse(RestClient.get(api_url))
    message = {}
    #Slice for unixtime in seconds because it is given in ms
    message['time_stamp'] = email['internalDate'].slice(0,10).to_i

    #check if email body is string (could be image)
    message["snippet"] = email['snippet'].gsub("&lt;", "<").gsub("&gt;",">").gsub("&#39;", "'").gsub("&quot;", "\"")
    # message['snippet'] = snippet

    #hanles emails that have 1 part
    if email['payload']['body']['data'] != nil
      text = email['payload']['body']['data']
      message['text'] = Base64.decode64(text.gsub("-", '+').gsub("_","/")).force_encoding("utf-8").to_s
      return message

    #handles common two part email
    #parts[0] gives plaintext parts[1] gives html
    elsif email['payload']['parts'][0]['body']['data'].class == String

      plain = email['payload']['parts'][0]['body']['data']
      #Convert mimebase64 into utf8
      message['text'] = Base64.decode64(plain.gsub("-", '+').gsub("_","/")).force_encoding("utf-8").to_s

      html = email['payload']['parts'][1]['body']['data']
      if html != nil
        message['html'] = Base64.decode64(html.gsub("-", '+').gsub("_","/")).force_encoding("utf-8").to_s
      end
      return message

    else
      #handles non-text interactions
      message['text'] = "Image Sent"
      message['snipet'] = "Image"
      return message
    end
  end

  #check if contact and user have interacted before
  def first_interaction?(contact)
    if Message.where(contact_id: contact.id) != []
      return false
    else
      return true
    end
  end

  def message_exist?(contact, timestamp)
    if Message.where(time_stamp: timestamp) != []
      return true
    else
      return false
    end
  end
  def twenty_nine_days?
    message = messages.first
    #days since last interaction
    days_since = ((message.time_stamp - Time.now.to_i)/86400.0).floor
    if days_since == 29
      return true
    else
      return false
    end
  end

  #check if you havent talked to your contact for 30 days
  def thirty_days?
    message = messages.first
    #days since last interaction
    days_since = ((message.time_stamp - Time.now.to_i)/86400.0).floor
    if days_since == 30
      return true
    else
      return false
    end
  end

  #update reminder for each contact
  def update_reminder
    #Time since last contact
    time_difference = (DateTime.now.strftime('%s').to_i) - (messages.order(time_stamp: :desc).first)
    #Status of interactions
    message_type = ( ((time_difference/86400) < 30) ? 'upcoming' : 'overdue')
    #Check if you should update an existing reminder or create a new one
    if (time_difference/86400) > 4
      if reminders == []
        Reminder.create(contact_id:id, reminder_type:message_type, message:messages.first.body_plain_text, time_since_last_contact:(time_difference/86400), user_id:user_id)
      else
        reminders.first.update(contact_id:id, reminder_type:message_type, message:messages.first.body_plain_text, time_since_last_contact:(time_difference/86400), user_id:user_id)
      end
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :ensure_logged_in

  #All contacts page
  def index
    #return json of all contacts if ajax
    if request.xhr?
        @contacts = Contact.all.where(user_id:current_user.id)
        @contacts_render = []
        @contacts.each do |contact|
          person = contact.as_json
          person['twitter_username'] = "@"+person['twitter_username']
          person['show'] = true
          @contacts_render << person
        end
        render json: @contacts_render
    else
      not_found
    end
  end

  #Show one user's info on click
  def show
    @contact = Contact.find(params[:id])
    respond_to do |format|
      #responds to ajax request and executes script on click
      format.js {}
    end
  end

  #Creating a new contact
  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id

    if @contact.twitter_username
      if @contact.twitter_username[0] == "@"
        @contact.twitter_username.slice!(0)
      end
      unless Misc.valid_handle(@contact.twitter_username)
        render "users/failure"
        return
      end
    end

    if @contact.save
      @contact.twitter_username = "@"+ @contact.twitter_username
      respond_to do |format|
        format.js{}
      end
    else
      head :internal_server_errror
    end

  end

  #Delete a contact
  def destroy
    @contact = Contact.find(params[:id])
    if @contact.user_id == current_user.id && @contact.destroy
      redirect_to user_path(current_user)
    else
      head :unauthorized
    end
  end

  def update
    @contact = Contact.find(params[:id])
    updated_info = contact_params

    if updated_info[:twitter_username][0] == "@"
      updated_info[:twitter_username].slice!(0)
    end

    unless Misc.valid_handle(updated_info[:twitter_username])
      render "users/failure"
      return
    end

    if @contact.user_id == current_user.id && @contact.update_attributes(updated_info)
      respond_to do |format|
        format.js{}
      end
    else
      head :unauthorized
    end
  end

  #Path is reached when the user is clicked on contacts index
  def edit
    @contact = Contact.find(params[:id])
    respond_to do |format|
      format.js {}  # to show the contacts info in form on all contacts page
    end
  end


  private
  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :category, :twitter_username)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_messages.html.erb
  <% contact.messages.each do |m| %>
  <div class="individual-message-div">
    <% date = Date.strptime(m.time_stamp.to_s, '%s') %>
    <div class='message_from_contact'>From: <%= @contact.name %></div>
    <div class='message_date'><%= "#{date.strftime("%h")} " + "#{date.day}" + ", #{date.year}" %></div><br>
    <div class='individual_message' data='<%=m.id%>'><%= m.snippet %>
        <div class='message_expand'><strong>expand message</strong><%= image_tag('expand-button.png', class:'expand-collapse-icon')%></div><br>
    </div>

    <% if m.body_html == nil %>
      <div class='individual_message_outer_div' id='<%=m.id%>' style='display:none'><div class='individual_message_div'><%= m.body_plain_text.to_s.html_safe%></div>
        <div class='message_expand'><strong>collapse message</strong> ^</div><br></div>
      </div>
    <% else %>
      <div class='individual_message_outer_div' id='<%=m.id%>' style='display:none'><div class='individual_message_div'><%= Nokogiri::HTML(m.body_html).at('body').to_s.html_safe %></div>
        <div class='message_expand'><strong>collapse message</strong><%= image_tag('up-arrow.png', class:'expand-collapse-icon')%> </div><br></div>
      </div>
    <% end %>
  </div>
  <% end %>

app/views/contacts/create.js.erb
var contact = <%= raw @contact.to_json %>
contact.show = true
window.all_contacts.push(contact)
fill_with_contacts(contact)
$(".modal").click()

app/views/contacts/edit.js.erb
$('.edit-modal').css('display', 'block');
var name = "<%= j(@contact.name)%>"
var phone = "<%= j(@contact.phone)%>"
var email = "<%= j(@contact.email)%>"
var id = <%= @contact.id%>
var category = "<%= j(@contact.category)%>"
var twitterUsername = "<%= j(@contact.twitter_username)%>"

$("input[name='contact[name]']").val(name);
$("input[name='contact[phone]']").val(phone);
$("input[name='contact[email]']").val(email);
$("input[name='contact[twitter_username]']").val(twitterUsername);
$("input[name='contact[category]']").val(category);

$("input[type='hidden']").attr('name', '_method');
$("input[type='hidden']").attr('value', 'patch');

$("form").attr("action","/contacts/" + id);

app/views/contacts/show.js.erb
$(function(){
  var email = "<%= j(@contact.email)%>"
  var name = "<%= j(@contact.name)%>"
  var id = <%= @contact.id%>
  $("#information").val("")

  var twitterUsername = "<%= j(@contact.twitter_username)%>"
  $("input[name='receiver']").val(email)
  $("#contact_name").text(name)
  var messages= "<%= j(render partial: "messages", locals: {contact: @contact})%>"
  $("#message-content").html(messages)

  $("#contact_id").val(id)
  $("#contact_id").html(id)
  $("#contact_new_info").val("")
  $("#subject_field").val("")
  $("#body_field").val("")
  $("#main-name").text(name);
  $("input[id='twitter-user-field']").val(twitterUsername);
  $("#send-text-area").text("@"+twitterUsername+ " ")
})

app/views/contacts/update.js.erb
window.all_contacts.forEach(function(contact){
  var updated_contact = <%= raw @contact.to_json %>
  if (contact.id === updated_contact.id){
    contact.name = updated_contact.name
    contact.phone = updated_contact.phone
    contact.email = updated_contact.email
    contact.category = updated_contact.category
    contact.twitter_username = "@"+updated_contact.twitter_username
    return contact
  }
})
$(".all-contacts-scroll-div").html("")
$(".edit-modal").click()
window.all_contacts.forEach(fill_with_contacts);

app/views/contacts/update_contact_patch.js.erb
window.all_contacts.forEach(function(contact){
  var updated_contact = <%= raw @contact.to_json %>
  if (contact.id === updated_contact.id){
    contact.name = updated_contact.name
    contact.phone = updated_contact.phone
    contact.email = updated_contact.email
    contact.category = updated_contact.category
    contact.twitter_username = updated_contact.twitter_username
    return contact
  }
})
$(".all-contacts-scroll-div").html("")
$(".edit-modal").click()
window.all_contacts.forEach(fill_with_contacts);

app/views/contacts/view.html.erb
<h1>THIS IS A FEED PAGE</h1>
<!-- all the messages go here for all the contacts -->
<%= link_to "All Contacts Page", contacts_url %><br>
<%= link_to "User Profile", '/users/1' %><br>
<%= link_to "Contact Profile", '/contacts/1' %><br>
<%= link_to "Add a Contact", new_contact_url %><br>