config/routes.rb
Rails.application.routes.draw do

  root 'pages#landing'
  get '/pull_messages' => 'pages#pull_messages'
  get '/link_to_twitter' => 'pages#twitter_sync'
  get '/auth/twitter/callback' => 'pages#twitter_callback'
  get '/googleauth' => 'pages#googleauth'
  get '/callback'=> 'pages#callback'
  post '/send' => 'messages#send_mail'
  get 'newsfeed' => 'pages#newsfeed'
  post '/direct_messages' => 'messages#create_direct_message'
  post '/tweets' => 'messages#create_tweet'
  get '/reminders' => 'reminders#index'
  get '/import_contacts' => "pages#import"
  get '/permission' => "pages#permission"
  resources :users, only: [:create, :update,:show]

  resources :contacts, only: [:show, :create, :destroy, :update, :index, :edit]

  resources :sessions, only: [:create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remindr</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.js' %>
  <%= csrf_meta_tags %>
  <script src="https://use.fontawesome.com/a9709a8405.js"></script>
  <%= yield :head %>
</head>
<body>

<div class="nav-bar">
  <%= link_to "Remindr", root_path, class:"logo" %>
    <% if current_user %>
      <%= link_to "LOG OUT", session_path("this session"), class:"logoutButton", :method => :delete %>
    <% else %>
      <%= link_to "LOG IN", "/", class:"loginButton" %>
    <%= link_to "SIGN UP", "/", class:"signup" %>
    <% end %>

    <% if current_user %>
      <!-- code to check if current user has overdue messages -->
      <% counter = 0 %>
      <% current_user.reminders.each do |reminder| %>
        <% if reminder.reminder_type == 'overdue' %>
          <% counter += 1 %>
          <% break %>
        <% end %>
      <% end %>
      <% if counter > 0 %>
        <%= link_to (image_tag "red_notification.svg"), reminders_path, class: "nav-icon"%>


      <% else %>
      <!-- code for nav links -->
        <%= link_to (image_tag "notification.svg"), reminders_path, class: "nav-icon" %>
      <% end %>
      <%= link_to (image_tag "ic_message_white_24px.svg"), newsfeed_path, class: "nav-icon" %>
      <%= link_to (image_tag "profile.svg"), user_path(current_user), class: "nav-icon"  %>

    <% end %>
</div>

<%= yield %>

</div>
</body>
</html>